pipeline {
    agent any

    stages {
        stage('Create EC2 Instance') {
            steps {
                script {
                    def ec2Params = [
                        region: 'ca-central-1',
                        credentials: 'terraform.admin',
                        imageId: 'ami-07413789aae50b0e0',
                        instanceType: 't2.micro',
                        keyName: 'jenkins-operations',
                        securityGroupId: 'sg-03cef694bd8017e60',
                        subnetId: 'subnet-07c29685c0def7cde',
                        tagSpecifications: [[resourceType: 'instance', tags: [[Key: 'Name', Value: 'My-First-Jenkins-Machine']]]]
                    ]
                    def instance = awsEC2Instance(ec2Params)
                    println "EC2 Instance ID: ${instance.id}"
                }
            }
        }

        stage('Create S3 Bucket') {
            steps {
                script {
                    def s3BucketName = 'my-first-jenkins-storage'
                    awsS3CreateBucket(bucketName: s3BucketName)
                    println "S3 Bucket '$s3BucketName' created successfully"
                }
            }
        }
    }
}
